[package]
name = "subversive"
version = "0.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
poc = []

[lib]
name = "subversive"
path = "src/lib.rs"

[dependencies]
tokio = { version = "1.36", features = ["full"] }
ed25519-dalek = { version = "2", features = ["rand_core"] }
rand_core = { version = "0.6", features = ["getrandom"] }
chrono = { version = "0.4", default-features = false, features = ["std", "clock"] }
zerocopy = { version = "0.7", features = ["derive"] }
zerocopy-derive = { version = "0.7" }
sha3 = "0.10"



