[package]
name = "p2p_network"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.36", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.11"
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
axum = "0.7"
axum-macros = "0.5.0-rc.1"
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "trace", "fs"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "time"] }
reqwest = { version = "0.11", features = ["json"] }
igd = { version = "0.12", features = ["aio"] }
rand = "0.8"
ctrlc = "3.4"
local-ip-address = "0.5"
polodb_core = "2.0"
polodb_bson = "2.0"
chrono = "0.4"
