[workspace]
members = [
    ".",
    "./packages/database",
    "./packages/network",
    "./packages/types",
    "./packages/utils",
    "./packages/shutdown",
    "./packages/crypto",
    "./packages/currency_engine",
    "./packages/ddns",
    "./packages/server",
]

[package]
name = "subversive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "subversive"
path = "src/lib.rs"

[dependencies]
subversive-database = { path = "./packages/database" }
subversive-network = { path = "./packages/network" }
subversive-types = { path = "./packages/types" }
subversive-shutdown = { path = "./packages/shutdown" }
subversive-utils = { path = "./packages/utils" }
subversive-crypto = { path = "./packages/crypto" }
subversive-server = { path = "./packages/server" }
tokio = { version = "1.36", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
log = "0.4"
env_logger = "0.11"
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
axum = { version = "0.8", features = ["macros"] }
axum-macros = "0.5.0-rc.1"
axum-server = { version = "0.6", features = ["tls-rustls"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "trace", "fs"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "time"] }
reqwest = { version = "0.11", features = ["json"] }
igd = { version = "0.12", features = ["aio"] }
ripemd = "0.1"
base58 = "0.2"
secp256k1 = { version = "0.27", features = ["rand"] }
rand = "0.8"
sha2 = "0.10"
ctrlc = "3.4"
local-ip-address = "0.5"
chrono = "0.4"
rustls = "0.22"
rustls-pemfile = "2.1"
tokio-rustls = "0.25"
rcgen = "0.12"  # For generating self-signed certificates
base64 = "0.21"  # For No-IP authentication
dns-lookup = "2.0.4"
uuid = { version = "1.0", features = ["v4"] }
rusqlite = { version = "0.30", features = ["bundled"] }
mockall = "0.13.1"
tempfile = "3.2"
async-trait = "0.1.88"
futures-util = "0.3.31"
rusty-leveldb = "3.0.2"

[dev-dependencies]
mockito = "1.2"
tempfile = "3.2"
tower = { version = "0.4", features = ["util"] }
hyper = { version = "0.14", features = ["full"] }
test-log = "0.2.17"
cargo-tarpaulin = "0.32.3"
