[package]
name = "subversive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.36", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
log = "0.4"
env_logger = "0.11"
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
axum = "0.8.1"
axum-macros = "0.5.0-rc.1"
axum-server = { version = "0.6", features = ["tls-rustls"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "trace", "fs"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "time"] }
reqwest = { version = "0.11", features = ["json"] }
igd = { version = "0.12", features = ["aio"] }
rand = "0.8"
ctrlc = "3.4"
local-ip-address = "0.5"
polodb_core = "2.0"
polodb_bson = "2.0"
chrono = "0.4"
rustls = "0.22"
rustls-pemfile = "2.1"
tokio-rustls = "0.25"
rcgen = "0.12"  # For generating self-signed certificates
base64 = "0.21"  # For No-IP authentication
dns-lookup = "2.0.4"
uuid = { version = "1.0", features = ["v4"] }

[dev-dependencies]
mockito = "1.2"
tempfile = "3.2"
tower = { version = "0.4", features = ["util"] }
hyper = { version = "0.14", features = ["full"] }