[package]
name = "subversive-shutdown"
version = "0.1.0"
edition = "2021"

[dependencies]
subversive-types = { path = "../types" }
subversive-network = { path = "../network" }
tokio = { version = "1.36", features = ["full"] }
anyhow = "1.0"
tracing = "0.1"


