[package]
name = "subversive-database"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
rusty-leveldb = "3.0.2"
tokio = { version = "1.36", features = ["full"] }
tracing = "0.1.41"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
subversive-crypto = { path = "../crypto" }
