[package]
name = "subversive-server"
version = "0.1.0"
edition = "2021"

[dependencies]
subversive-database = { path = "../database" }
subversive-network = { path = "../network" }
subversive-types = { path = "../types" }
subversive-utils = { path = "../utils" }
subversive-crypto = { path = "../crypto" }
subversive-shutdown = { path = "../shutdown" }
tokio = { version = "1.36", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
axum = { version = "0.8", features = ["macros"] }
axum-macros = "0.5.0-rc.1"
axum-server = { version = "0.6", features = ["tls-rustls"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "trace", "fs"] }
tracing = "0.1"
anyhow = "1.0"
reqwest = { version = "0.11", features = ["json"] }
chrono = "0.4"
