[package]
name = "subversive-ddns"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
base64 = "0.21"
reqwest = { version = "0.11", features = ["json"] }
tracing = "0.1"

[dev-dependencies]
mockito = "1.2"
tokio = { version = "1.0", features = ["rt", "macros"] }
