[package]
name = "subversive-crypto"
version = "0.1.0"
edition = "2021"

[lib]
name = "subversive_crypto"
path = "src/lib.rs"

[dependencies]
subversive-utils = { path = "../utils" }
base58 = "0.2.0"
rand = { version = "0.8", features = ["std"] }
ripemd = "0.1.3"
secp256k1 = { version = "0.30.0", features = ["rand"] }
sha2 = "0.10.8"
tracing = "0.1.41"
ed25519-dalek = { version = "2.1.1", features = ["rand_core"] }